<html>
<body>
   <footer>
        <div id="footer">
            <div id="twitter">
                <h3>TWITTER FEED</h3>
                <time datetime="2012-10-23"><a href="#">23 oct</a></time>
                <p>Мы приветствуем вас! На данном сайте вы сможете узнать наши 
                    ближайшие точки, где вы сможете увлечся игрой в боулинг.
                    Мы можете посмотреть даты турниров на ближайший месяц здесь. 
                    Чтобы заказать дорожку нужно здесь всего лишь ввести контактные 
                    данные, время (количество часов) игры и номер количество дорожек, 
                    если вы играете большой компанией людей.</p>
            </div>
            <div id="sitemap">
                <h3>SITEMAP</h3>
                <div>
                    <a href="/index.php?page=main">Главная</a>
                    <a href="/index.php?page=about">О нас</a>
                    <a href="/index.php?page=order">Заказ</a>
                </div>
                <div>
                    <a href="/index.php?page=balls">Шары</a>
                    <a href="/index.php?page=roads">Дорожки</a>
                    <a href="/index.php?page=turnir">Турниры</a>
                </div>
            </div>
            <div id="social">
                <h3>SOCIAL NETWORKS</h3>
                <a href="http://twitter.com/" class="social-icon twitter"></a>
                <a href="http://facebook.com/" class="social-icon facebook"></a>
                <a href="http://plus.google.com/" class="social-icon google-plus"></a>
                <a href="http://vimeo.com/" class="social-icon-small vimeo"></a>
                <a href="http://youtube.com/" class="social-icon-small youtube"></a>
                <a href="http://flickr.com/" class="social-icon-small flickr"></a>
                <a href="http://instagram.com/" class="social-icon-small instagram"></a>
                <a href="/rss/" class="social-icon-small rss"></a>
            </div>
            <div id="footer-logo">
                <a href="/"><img src="../img/logo.png" alt="Whitesquare logo"></a>
                <p>Copyright &copy; 2012 Whitesquare. A <a href="http://pcklab.com">pcklab</a> creation </p>
            </div>
        </div>
    </footer>

</body>
</html>